### ISSUE TITLE
【依頼】フリマアプリ挙動確認

### ISSUE THREAD

**Issue by Tomoka17** [Tomoka17/furima-37718#21]
# URL
https://furima-37718.herokuapp.com/

# Basic認証のIDとパスワード 
ID: admin
Password: 2222

# 出品者用のメールアドレスとパスワード 
メールアドレス: ttt@ttt.jp
パスワード: t000000

# 購入者用のメールアドレスとパスワード 
メールアドレス: hhh@hhh.jp
パスワード: h000000

**Comment by snkw-works** [comment]
@Tomoka17 さん、ご提出ありがとうございます‼︎
動作の確認をしたところ、修正していただきたい箇所がございました。
以下のご確認をお願いします！

[修正依頼箇所]
- [x] **ログイン状態の場合でも、売却済みの商品には、「商品の編集」「削除」「購入画面に進む」ボタンが表示されないよう修正しましょう**
売却済みの商品にも「購入画面に進む」ボタンが表示されてしまいます。
<img width="1440" alt="スクリーンショット 2022-04-08 12 17 58" src="https://user-images.githubusercontent.com/54050089/162356161-1eb8a08b-b20e-4404-a982-e420a4e53b20.png">


- [x] **ログアウト状態の場合は、商品の販売状況に関わらず、「商品の編集」「削除」「購入画面に進む」ボタンが表示されないよう修正しましょう**
"ログアウト状態のユーザー"にも、販売状況に関わらず「購入画面に進む」ボタンが表示されています。

修正が完了しましたら、再度以下の最終課題完了報告フォームのご提出をお願いします！
※新しいissueを作っていただく必要はございません。
※質問等でコメントした場合も都度フォームのご提出をお願いします。
https://forms.gle/dYuR1wjeHepbEhU7A

**Comment by Tomoka17** [comment]
購入機能実装の際にshow.html.erbのボタン表示の条件分岐において、<% else %>の後が何も記述がないため消すようにご指摘いただき、その部分を削除しました。
削除した部分を再度元に戻しましたが、条件分岐の仕方が誤っているのでしょうか？
ご確認お願いいたします。

**Comment by shodai-ito** [comment]
@Tomoka17 さん、再提出とご質問ありがとうございます！

show.html.erbファイルの<% else %>の記述についてこちらで確認しましたが、有無にかかわらず正常な挙動が確認できました。
コミット履歴を確認させていただきましたが、先の指摘以前は
`<% else user_signed_in? && @item.order.blank? %>`
と記述されており、それを今回
`<% elsif user_signed_in? && @item.order.blank? %>`
 と修正いただいたかと存じます。
先の挙動のトラブルは、「elsif」でなく「else」を用いていたことが原因と考えられますので、今回新たに追記された記述のない<% else %>は指摘通り削除いただいて問題ありません。

現状、動作自体は正常であることが確認できましたので、LGTMとさせていただきます！　
おめでとうございます🎉


**※確認したのは必須機能のみです。追加実装した機能については確認しておりません。
そのため追加機能を実装している場合は、正しく想定通りの挙動であるか、再度ご自身でご確認をお願いいたします。**
**※Github上の最終課題の履歴はここまで頑張ってきた証です。削除せず大切に保管するようにしましょう。**

ここまで培ってきた知識や学びを活かして、これからは下記例のようなさらなる学習に取り組みましょう！

＜今後の学習例＞
・フリマアプリ追加実装
・オリジナルアプリ開発
・今まで学んできた言語あるいは新言語の学習　等
今後の学習方針や学習計画については、担当ライフコーチまでお気軽にご相談くださいませ。
また、以下提出物に関するリマインドです。

＜提出物＞
・最終課題説明文（フリマアプリ達成要件および、追加実装内容にて作成をお願いいたします）
・要件定義（追加実装あるいは、オリジナルアプリの内容で作成をお願いいたします）
※提出期日については、最終課題開始時に配布した下記動画にてご確認いただきますようお願いいたします。

＜最終課題に関する締め切りについての動画＞
https://master.tech-camp.in/v2/curriculums/7105

今後の流れに関して、もしご不明点がございましたら、
担当ライフコーチまでお気兼ねなくお申し付けくださいませ。
